### ISSUE TITLE
运行客户端命令遇错

### ISSUE THREAD

**Issue by briteming** [tobyxdd/hysteria#10]
hi.

我在mac上运行：
./cmd proxy client -server vps-ip:36710 -socks5-addr localhost:1081 -up-mbps 10 -down-mbps 50 -obfs BlueberryFaygo -username xyz -password abc
显示：
...
2020/05/03 16:28:07 Client initialization failed: CRYPTO_ERROR: x509: cannot validate certificate for my-vps-ip because it doesn't contain any IP SANs.

怎么解决？

**Comment by mritd** [comment]
你的服务端证书有问题，服务端证书没有包含服务端 ip 或者不是通过域名访问的服务器；如果自己有域名的话就通过 let's encrypt(acme) 自己签署一个，没有就使用自签证书。

**Comment by tobyxdd** [comment]
服务端证书是什么域名你客户端就要用什么域名连接

**Comment by xtccc** [comment]
服务端的 .cert 证书 换成全链证书 fullchain.cer 试试？
