### ISSUE TITLE
可否增加单端口多用户和流量统计的支持？

### ISSUE THREAD

**Issue by getizumo** [tobyxdd/hysteria#41]
hysteria的速度确实非常快，感谢作者开源。

现在hysteria只适用于自建服务器的用户。请问是否考虑加上单端口多用户和流量统计等功能？这样服务提供商也可以把hysteria加进来，让更多的人用到。

**Comment by tobyxdd** [comment]
多用户是已经计划在下个版本加入的功能，服务端会新增一种 `external` auth 模式支持由外部 HTTP API 处理验证。

流量统计的话，你大概想要什么形式的接口？

**Comment by getizumo** [comment]
太好了。

流量统计的需求大概如下：

- 统计每个用户的上传和下载字节
- 持久化，即使服务端程序重启也不会丢失统计数据
- 提供清零的接口，可以单独清零某个用户的流量统计
- API接口端口号可自定义，格式无所谓，HTTP+JSON或其它都可以

**Comment by tobyxdd** [comment]
这样恐怕有点麻烦，如果是主动推送呢？提供一个 API endpoint 和一个 interval，hysteria 每过一段时间就把这段时间内每个用户每个连接的流量数据提交上去。

**Comment by tobyxdd** [comment]
如果 endpoint 返回的状态不是 HTTP 200 则保留状态等下一次一起提交，这样统计后端挂了也不会丢状态。只是如果 Hysteria 自己挂了就会丢失不超过一个 interval 的状态，不要求 100% 精确的话问题不大，interval 可以设短些。

**Comment by mritd** [comment]
尝试暴露一个普罗米修斯的监控？

**Comment by getizumo** [comment]
那样的话，直接支持普罗米修斯可以吗？类似这样：

https://github.com/wi1dcard/v2ray-exporter

**Comment by tobyxdd** [comment]
可以，那我做一个类似的吧

**Comment by tobyxdd** [comment]
顺便这是会带在下个 release 的 HTTP external auth 的用法

https://github.com/tobyxdd/hysteria/blob/22ad36dabb273403e3ba14a17995cfd10f2cc844/README.zh.md#%E6%8E%A5%E5%85%A5%E5%A4%96%E9%83%A8%E9%AA%8C%E8%AF%81

**Comment by getizumo** [comment]
感谢。

关于验证，有几个问题：

1. POST请求中的 `send` 和 `recv` 有什么实际影响吗？
2. 返回时是根据 `ok` 等于 `true` 或者 `false` 来决定对吗？ `msg` 有什么用？是必须的吗？
3. 这个请求的超时时间是多少？

另外有个建议，就是统一变量名和单位。比如：

1. `send` 应该对应 `receive` ，如果用 `recv` ，则发送应为 `snd` ；
2. `up` 和 `down` 以及 `send` 和 `recv` 应该统一；
3. mbps和bps应该统一。

**Comment by tobyxdd** [comment]
1. 没有实际影响，可供 logging
2. 是根据 `ok` 来的，msg 也是 Hysteria 协议里的一个字段，可以用来传递错误原因等
3. 10s

1. POSIX 就是用的 `send` `recv`
2. 这个有道理，未来考虑改下
3. 客户端后面改成 bps 吧，或者至少新增 bps 的配置字段

**Comment by tobyxdd** [comment]
看看这个如何？

https://github.com/tobyxdd/hysteria/tree/wip-prometheus#prometheus-metrics

**Comment by getizumo** [comment]
很棒！期待新版本。

**Comment by humbass** [comment]
> 如果 endpoint 返回的状态不是 HTTP 200 则保留状态等下一次一起提交，这样统计后端挂了也不会丢状态。只是如果 Hysteria 自己挂了就会丢失不超过一个 interval 的状态，不要求 100% 精确的话问题不大，interval 可以设短些。

push 的方法很好哇，后端只要做一个接受就行了。

**Comment by 17huiwei** [comment]
多用户现在支持了么？

**Comment by haruue** [comment]
> @17huiwei: 多用户现在支持了么？

多用户只需在服务端配置文件 `"auth"` 里面的 `"config"` 数组指定多个密码即可。

```json
"auth": {
  "mode": "passwords",
  "config": ["用户1密码", "用户2密码", "用户3密码"]
},
```
