### ISSUE TITLE
socks udp issue

### ISSUE THREAD

**Issue by hdid** [tobyxdd/hysteria#47]
It seems that udp function does not work properly (or maybe i'm wrong1?). I used hysteria with tun2socks but dns lookups could not be processed (but for example v2ray client' socks could process the dns requests).

**Comment by tobyxdd** [comment]
Do you mind sharing your config? Remove sensitive info like the address and password of course

**Comment by hdid** [comment]
Sure;
```
{
  "server": "ip:port",
  "obfs": "xxxxxxxxxxxxxxx",
  "up_mbps": 25,
  "down_mbps": 60,
  "socks5": {
    "listen": ":1080"
  }
}
```

**Comment by tobyxdd** [comment]
Can you test the SOCKS5 proxy with `udpchk.py` under `docs/socks5`?

**Comment by tobyxdd** [comment]
I might have found a possible reason. Can you also try changing the SOCKS5 listen address to `127.0.0.1:1080` instead of `:1080`? Or your actual IP if it's for other devices

**Comment by hdid** [comment]
> 
> 
> Can you test the SOCKS5 proxy with `udpchk.py` under `docs/socks5`?

```
root@machine:/tmp/hysteria/docs/socks5## python ./udpchk.py
UDP check passed
```
One interesting thing; The test passed with hysteria but did not pass with v2ray client! (while v2ray client works well with udp and dns requests)




> 
> 
> I might have found a possible reason. Can you also try changing the SOCKS5 listen address to `127.0.0.1:1080` instead of `:1080`? Or your actual IP if it's for other devices

I did but no success.

**Comment by tobyxdd** [comment]
That's weird because I've tested it with [Clash](https://github.com/Fndroid/clash_for_windows_pkg) and [Kistunebi](https://play.google.com/store/apps/details?id=fun.kitsunebi.kitsunebi4android), and they both worked perfectly.

Will further look into this.

**Comment by tobyxdd** [comment]
One more thing, are you using tun2socks directly, or are you using some proxy tool that comes with it?

**Comment by hdid** [comment]
> 
> 
> One more thing, are you using tun2socks directly, or are you using some proxy tool that comes with it?

I use  @xjasonlyu' tun2socks fork on Debian OS . Today tested with go-tun2socks but same result occurred.

**Comment by hdid** [comment]
> 
> 
> One more thing, are you using tun2socks directly, or are you using some proxy tool that comes with it?

Yes i use  @xjasonlyu' tun2socks fork alone running on Debian OS . Today tested with go-tun2socks but same result occurred.

**Comment by hdid** [comment]
```
root@machine:~# v2ray -config /usr/local/etc/v2ray/config.json
root@machine:~# ./tun2socks -device tun://tun0 -proxy socks5://127.0.0.1:1080
root@machine:~# ip addr add 10.20.30.1/24 dev tun0
root@machine:~# ip link set dev tun0 up
root@machine:~# ip route add serverip via defaultgw
root@machine:~# ip route replace default via 10.20.30.1 dev tun0
```
After this everything work (for example i can run `dig` command and see it's response). but when i replace v2ray with hysteria just tcp requests go through proxy but udp has no effect. About routing; i do not see any error about.

**Comment by tobyxdd** [comment]
Can you try the latest code on the master branch? I think I've solved it

**Comment by tobyxdd** [comment]
https://github.com/tobyxdd/hysteria/commit/b09880a0505b7617adb2716490c85a1e376b8625#diff-c168ff4e9b196d4af53e99ce3f1bb64a8699cfbe7a54c18629377ec0fe2d7a86R314

**Comment by hdid** [comment]
by v0.6.0 release; yes the issue has been resolved.
Thank you 👍
